### PR TITLE
Hal fixes for msm8952 

### PR DESCRIPTION
**Pull request by nvdx11**

### CODE REVIEW

**Comment by oadam11** [comment]
+1
needed for Athene

**Comment by nvdx11** [comment]
I had it on kenzo, fixed now with these commits!

**Comment by premaca** [comment]
we need to get them through Gerrit now. Will check soon.

**Comment by premaca** [comment]
I pushed to gerrit, https://review.gzospgzr.com/#/c/53/

**Comment by nvdx11** [comment]
@premaca nice,btw i've also pulled in display msm8952 check it out too

**Pull request closed without merging**
